### ISSUE TITLE
Reproduce CIFAR-10 Semi-Supervised

### ISSUE THREAD

**Issue by christiancosgrove** [openai/improved-gan#23]
Has anyone managed to reproduce the exact results for semi-supervised learning using `train_cifar_feature_matching.py`? With the default hyperparameters and 4000 labeled examples, I'm overfitting and getting 32% test error after 48 epochs. Getting 0.5% training error. Paper claims to get test error of only 18.6% on this task. 

Do I need to train longer (for the full 1200 epochs?), or are others having this same problem?

**Comment by christiancosgrove** [comment]
After a few more hours of training, test error continues to drop; default hyperparams seem to be working. It seems that training the networks to produce realistic samples and training to do semi-supervised learning happen at different timescales.

**Comment by alpapado** [comment]
About how many epochs are required before the test error gets close to the value reported in the paper?

**Comment by zychen2016** [comment]
Hello!why discriminator dense layer just have 10 units? why not 10+1(real/fake)？

**Comment by daixiangzi** [comment]
> Hello!why discriminator dense layer just have 10 units? why not 10+1(real/fake)？

because other(11) class be eliminated,
![图片](https://user-images.githubusercontent.com/24811131/69898059-18782700-138f-11ea-8eae-9940d88b1d1a.png)

**Comment by daixiangzi** [comment]
> Has anyone managed to reproduce the exact results for semi-supervised learning using `train_cifar_feature_matching.py`? With the default hyperparameters and 4000 labeled examples, I'm overfitting and getting 32% test error after 48 epochs. Getting 0.5% training error. Paper claims to get test error of only 18.6% on this task.
> 
> Do I need to train longer (for the full 1200 epochs?), or are others having this same problem?

i meet same problem,final your results test erro?
